name: AuthorizationServer-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src/AuthorizationServer.sln
    - name: Build
      run: dotnet build --no-restore --configuration ${{CONFIGURATION}} --verbosity normal src/AuthorizationServer.sln
    - name: Test
      run: dotnet test --no-build --configuration ${{CONFIGURATION}} --verbosity normal src/AuthorizationServer.sln
    - name: Publish
      run: dotnet publish --no-build --configuration Release --verbosity normal src/AuthorizationServer.sln
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: AuthorizationServer
        path: src/bin/${{CONFIGURATION}}/netcoreapp3.1/publish
